name: Keep Alive
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: date > .last-updated
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - run: git commit -m "keep alive" || true
      - run: git push
